"""Add vendor_address column to receipts

Revision ID: 2907bb853969
Revises: e3ee62e2121f
Create Date: 2025-11-15 11:11:52.929759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2907bb853969'
down_revision = 'e3ee62e2121f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendor_address', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.drop_column('vendor_address')

    # ### end Alembic commands ###
